# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6caafdbd016c0eec718a763226a2715f52630dcaa5d05745cb05f89cb385aaccfcf8a99f868ff80bafe9ffc25aceceb11954666225a90356cb76c1689894387

test:
  secret_key_base: daff8f8b029ee7711aa101bf9130001137d3e88d9261cee994c8ab04d4b89930996259b3da3cc7353dffea14c03d1a41a0fd8d2b1a1b0095b4076dc62d5bd8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
